INSERT INTO MOVIES (TITLE, RUNTIME, GENRE, IMDB_SCORE, RATING) VALUES ('Howard The Duck', 110, 'Sci-Fi', 4.6, 'PG');
INSERT INTO MOVIES (TITLE, RUNTIME, GENRE, IMDB_SCORE, RATING) VALUES ('Starship Troopers', 129, 'Sci-Fi', 7.2, 'PG-13'), ('Waltz With Bashir', 90, 'Documentary', 8.0, 'R'), ('Spaceballs', 96, 'Comedy', 7.1, 'PG'), ('Monsters Inc.', 92, 'Animation', 8.1, 'G');

SELECT * FROM MOVIES WHERE GENRE = 'Sci-Fi';
SELECT * FROM MOVIES WHERE IMDB_SCORE >= 6.5;
SELECT * FROM MOVIES WHERE RUNTIME < 100 AND (RATING = 'G' OR RATING = 'PG');
SELECT GENRE, AVG(RUNTIME) FROM MOVIES WHERE IMDB_SCORE < 7.5 GROUP BY GENRE;
UPDATE MOVIES SET RATING = 'R' WHERE TITLE = 'Spaceballs';
